import type { CountryRecord } from "./types";

export const countries: CountryRecord[] = [
  {
    country: "Australia",
    region: "APAC",
    regulator: "ASIC / APRA / AUSTRAC",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Allowed with restrictions",
    pspRisk: "Medium",
    walletLicenseExists: "Yes",
    walletLicenseType: "Purchased payment facility / non-cash payment facility",
    foreignWalletAllowed: "Conditional",
    walletRisk: "Medium",
    recommendedEntryModel: "Cross-border orchestration with legal review; local partner for stored value if needed",
    strictnessScore: 3,
    notes: "Processing can be feasible, but non-cash payment facility and stored value concepts may trigger licensing depending on structure."
  },
  {
    country: "Bangladesh",
    region: "APAC",
    regulator: "Bangladesh Bank",
    pspLicenseRequired: "Yes",
    crossBorderProcessing: "Not allowed / requires licence",
    pspRisk: "High",
    walletLicenseExists: "Yes",
    walletLicenseType: "PSP/PSO and e-money issuance under Bangladesh Bank regime",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Local licensed partner only",
    strictnessScore: 5,
    notes: "High-friction market with statutory licensing perimeter for payment services and wallet-like activities."
  },
  {
    country: "Brazil",
    region: "LATAM",
    regulator: "Central Bank of Brazil",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Allowed with restrictions",
    pspRisk: "Medium",
    walletLicenseExists: "Yes",
    walletLicenseType: "Payment institution – issuer of e-money / payment accounts",
    foreignWalletAllowed: "Conditional",
    walletRisk: "High",
    recommendedEntryModel: "Cross-border processing with licensed local arrangements; local partner for wallet",
    strictnessScore: 4,
    notes: "Payment institutions are regulated, including acquirers and e-money issuers; local structuring is usually needed."
  },
  {
    country: "Canada",
    region: "North America",
    regulator: "Bank of Canada / FINTRAC",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Allowed with restrictions",
    pspRisk: "Medium",
    walletLicenseExists: "No dedicated e-money licence",
    walletLicenseType: "RPAA registration + safeguarding; FINTRAC registration as applicable",
    foreignWalletAllowed: "Conditional",
    walletRisk: "Medium",
    recommendedEntryModel: "Cross-border with registration if targeting Canada",
    strictnessScore: 3,
    notes: "Foreign PSPs targeting end users in Canada can be explicitly captured under the retail payments framework."
  },
  {
    country: "Chile",
    region: "LATAM",
    regulator: "CMF / Central Bank of Chile",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Allowed with restrictions",
    pspRisk: "Medium-High",
    walletLicenseExists: "Yes",
    walletLicenseType: "Prepaid payment methods / payment card issuer-operator framework",
    foreignWalletAllowed: "Conditional",
    walletRisk: "Medium-High",
    recommendedEntryModel: "Cross-border processing only with local regulatory review; partner-led model preferred",
    strictnessScore: 4,
    notes: "Cross-border acquiring and processing have explicit regulatory treatment and may require registration."
  },
  {
    country: "China",
    region: "APAC",
    regulator: "People's Bank of China",
    pspLicenseRequired: "Yes",
    crossBorderProcessing: "Not allowed / requires licence",
    pspRisk: "High",
    walletLicenseExists: "Yes",
    walletLicenseType: "Payment business permit / non-bank payment institution licence",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Local licensed partner only",
    strictnessScore: 5,
    notes: "Highly regulated market; payment services and stored value are tightly controlled under licensing rules."
  },
  {
    country: "Colombia",
    region: "LATAM",
    regulator: "Superintendencia Financiera de Colombia / Banco de la República",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Allowed with restrictions",
    pspRisk: "Medium-High",
    walletLicenseExists: "Yes",
    walletLicenseType: "SEDPE / related supervised electronic deposits and payments regimes",
    foreignWalletAllowed: "Conditional",
    walletRisk: "High",
    recommendedEntryModel: "Partner-led model; avoid direct wallet launch",
    strictnessScore: 4,
    notes: "Wallet-like products usually require local supervised structures; payments modernization increases scrutiny."
  },
  {
    country: "Egypt",
    region: "MEA",
    regulator: "Central Bank of Egypt",
    pspLicenseRequired: "Yes",
    crossBorderProcessing: "Not allowed / requires licence",
    pspRisk: "High",
    walletLicenseExists: "Yes",
    walletLicenseType: "CBE-licensed PSP/EMI framework",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Local licensed partner only",
    strictnessScore: 5,
    notes: "Recent licensing rules formalize a strict perimeter for domestic and foreign-based payment institutions."
  },
  {
    country: "Hong Kong",
    region: "APAC",
    regulator: "Hong Kong Monetary Authority",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Allowed with restrictions",
    pspRisk: "Low-Medium",
    walletLicenseExists: "Yes",
    walletLicenseType: "Stored Value Facility licence",
    foreignWalletAllowed: "Conditional",
    walletRisk: "Medium-High",
    recommendedEntryModel: "Cross-border processing; local structure or licence for wallet",
    strictnessScore: 2,
    notes: "Processing can often be structured cross-border, but stored value facilities are explicitly regulated."
  },
  {
    country: "India",
    region: "APAC",
    regulator: "Reserve Bank of India",
    pspLicenseRequired: "Yes",
    crossBorderProcessing: "Not allowed / requires authorisation",
    pspRisk: "High",
    walletLicenseExists: "Yes",
    walletLicenseType: "Prepaid Payment Instruments (PPI) authorisation",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Local licensed partner only",
    strictnessScore: 5,
    notes: "Payment aggregator and wallet activities are tightly regulated; foreign direct launch is high-risk."
  },
  {
    country: "Indonesia",
    region: "APAC",
    regulator: "Bank Indonesia",
    pspLicenseRequired: "Yes",
    crossBorderProcessing: "Not allowed / requires licence",
    pspRisk: "High",
    walletLicenseExists: "Yes",
    walletLicenseType: "BI e-money issuer approval",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Local licensed partner only",
    strictnessScore: 5,
    notes: "Payment service providers and e-money are within Bank Indonesia’s clear licensing perimeter."
  },
  {
    country: "Japan",
    region: "APAC",
    regulator: "Financial Services Agency of Japan",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Allowed with restrictions",
    pspRisk: "Medium",
    walletLicenseExists: "Yes",
    walletLicenseType: "Prepaid Payment Instruments / Funds Transfer Service Provider",
    foreignWalletAllowed: "Conditional",
    walletRisk: "Medium",
    recommendedEntryModel: "Cross-border processing with careful legal analysis; direct licence if scale justifies",
    strictnessScore: 3,
    notes: "Payment services rules are effects-based and activity-specific; local presence may be needed for some models."
  },
  {
    country: "Kenya",
    region: "MEA",
    regulator: "Central Bank of Kenya",
    pspLicenseRequired: "Yes",
    crossBorderProcessing: "Not allowed / requires authorisation",
    pspRisk: "High",
    walletLicenseExists: "Yes",
    walletLicenseType: "E-money issuer authorisation + PSP authorisation",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Local licensed partner only",
    strictnessScore: 5,
    notes: "Both PSP and wallet models are explicitly regulated under the national payment framework."
  },
  {
    country: "South Korea",
    region: "APAC",
    regulator: "Financial Services Commission / Financial Supervisory Service",
    pspLicenseRequired: "Yes",
    crossBorderProcessing: "Not allowed / requires registration/licence",
    pspRisk: "High",
    walletLicenseExists: "Yes",
    walletLicenseType: "Prepaid electronic payment instrument / electronic financial business categories",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Local licence or acquisition; otherwise local partner only",
    strictnessScore: 5,
    notes: "Highly permissioned market; foreign entrants often need local licences or licensed acquisitions."
  },
  {
    country: "Malaysia",
    region: "APAC",
    regulator: "Bank Negara Malaysia",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Allowed with restrictions",
    pspRisk: "Medium",
    walletLicenseExists: "Yes",
    walletLicenseType: "BNM e-money issuer approval",
    foreignWalletAllowed: "Conditional",
    walletRisk: "Medium-High",
    recommendedEntryModel: "Cross-border orchestration for processing; local partner for domestic wallet/rails",
    strictnessScore: 4,
    notes: "Permissioned framework for major payment and e-money activities; local structures are common."
  },
  {
    country: "Mexico",
    region: "LATAM",
    regulator: "CNBV / Banco de México",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Allowed with restrictions",
    pspRisk: "Medium-High",
    walletLicenseExists: "Yes",
    walletLicenseType: "IFPE (Electronic Payment Funds Institution)",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Partner-led model with local licensed entities",
    strictnessScore: 4,
    notes: "Stored funds and payment account models are centrally regulated under the fintech law."
  },
  {
    country: "New Zealand",
    region: "APAC",
    regulator: "Financial Markets Authority / Department of Internal Affairs",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Allowed",
    pspRisk: "Low",
    walletLicenseExists: "No dedicated e-money licence",
    walletLicenseType: "Product-dependent; registration/AML analysis",
    foreignWalletAllowed: "Conditional",
    walletRisk: "Medium",
    recommendedEntryModel: "Cross-border orchestration",
    strictnessScore: 2,
    notes: "One of the lower-friction markets, though product structure and AML scope still matter."
  },
  {
    country: "Pakistan",
    region: "APAC",
    regulator: "State Bank of Pakistan",
    pspLicenseRequired: "Yes",
    crossBorderProcessing: "Not allowed / requires authorisation",
    pspRisk: "High",
    walletLicenseExists: "Yes",
    walletLicenseType: "Electronic Money Institution (EMI) licence",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Local licensed partner only",
    strictnessScore: 5,
    notes: "Cross-border e-money and payment services are tightly controlled under a formal authorization regime."
  },
  {
    country: "Philippines",
    region: "APAC",
    regulator: "Bangko Sentral ng Pilipinas",
    pspLicenseRequired: "Yes (OPS registration + activity approvals)",
    crossBorderProcessing: "Allowed with restrictions",
    pspRisk: "Medium-High",
    walletLicenseExists: "Yes",
    walletLicenseType: "Electronic Money Issuer (EMI)",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Licensed local partner preferred",
    strictnessScore: 4,
    notes: "OPS and EMI perimeters make direct unlicensed operation risky for both payment and wallet activity."
  },
  {
    country: "Singapore",
    region: "APAC",
    regulator: "Monetary Authority of Singapore",
    pspLicenseRequired: "Yes",
    crossBorderProcessing: "Allowed (if licensed)",
    pspRisk: "Low",
    walletLicenseExists: "Yes",
    walletLicenseType: "SPI / MPI for e-money issuance and other payment services",
    foreignWalletAllowed: "Conditional",
    walletRisk: "Medium",
    recommendedEntryModel: "Home licence / primary governance hub",
    strictnessScore: 2,
    notes: "Clear and predictable regime; ideal base jurisdiction but still licensing-driven."
  },
  {
    country: "South Africa",
    region: "MEA",
    regulator: "South African Reserve Bank / PASA",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Allowed with restrictions",
    pspRisk: "Medium",
    walletLicenseExists: "Yes (historically constrained)",
    walletLicenseType: "Historically bank-led e-money issuance; reforms evolving",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Sponsor-bank / local partner model",
    strictnessScore: 3,
    notes: "Current posture is restrictive for non-bank wallet issuance, though reforms may broaden access over time."
  },
  {
    country: "Taiwan",
    region: "APAC",
    regulator: "Financial Supervisory Commission / Ministry of Digital Affairs",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Allowed with restrictions",
    pspRisk: "Medium-High",
    walletLicenseExists: "Yes",
    walletLicenseType: "Electronic Payment Institution licence",
    foreignWalletAllowed: "Conditional",
    walletRisk: "High",
    recommendedEntryModel: "Local partner for wallet and regulated collection flows",
    strictnessScore: 4,
    notes: "Dual regime for electronic payment institutions and third-party payment providers increases compliance complexity."
  },
  {
    country: "Thailand",
    region: "APAC",
    regulator: "Bank of Thailand / Ministry of Finance",
    pspLicenseRequired: "Yes",
    crossBorderProcessing: "Not allowed / requires licence",
    pspRisk: "High",
    walletLicenseExists: "Yes",
    walletLicenseType: "E-money service business under Payment Systems Act",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Local licensed partner only",
    strictnessScore: 5,
    notes: "Payment systems and e-money are clearly regulated; direct offshore launch is high-risk."
  },
  {
    country: "Turkey",
    region: "EMEA",
    regulator: "Central Bank of the Republic of Türkiye",
    pspLicenseRequired: "Yes",
    crossBorderProcessing: "Not allowed / requires licence",
    pspRisk: "High",
    walletLicenseExists: "Yes",
    walletLicenseType: "Electronic money institution licence",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Local licensed partner only",
    strictnessScore: 5,
    notes: "Payment institutions and electronic money institutions are formally licensed and supervised."
  },
  {
    country: "United States",
    region: "North America",
    regulator: "FinCEN + state regulators",
    pspLicenseRequired: "Conditional",
    crossBorderProcessing: "Grey area / Allowed with restrictions",
    pspRisk: "Medium-High",
    walletLicenseExists: "Yes (fragmented)",
    walletLicenseType: "State money transmitter licensing + federal MSB perimeter",
    foreignWalletAllowed: "Conditional",
    walletRisk: "High",
    recommendedEntryModel: "Partner-led initially; direct licensing only if volume justifies",
    strictnessScore: 4,
    notes: "State-by-state licensing is the biggest friction point, especially for settlement and wallet-like functions."
  },
  {
    country: "Vietnam",
    region: "APAC",
    regulator: "State Bank of Vietnam",
    pspLicenseRequired: "Yes",
    crossBorderProcessing: "Not allowed / requires licence",
    pspRisk: "High",
    walletLicenseExists: "Yes",
    walletLicenseType: "Intermediary payment services licence (includes e-wallet)",
    foreignWalletAllowed: "No",
    walletRisk: "High",
    recommendedEntryModel: "Local licensed partner only",
    strictnessScore: 5,
    notes: "Payment intermediary and e-wallet functions sit within a strict SBV approval framework."
  }
];
